# Generated by Django 5.1.4 on 2024-12-27 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildIT_API', '0007_alter_users_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BuildIT_API.users'),
        ),
        migrations.AlterField(
            model_name='items',
            name='effort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='placement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='priority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='risk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', max_length=15),
        ),
    ]
