# Generated by Django 5.1.4 on 2024-12-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildIT_API', '0009_alter_items_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
