# Generated by Django 5.1.4 on 2025-01-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildIT_API', '0012_tags_project_alter_items_name_alter_users_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='markdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='project_placement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='user_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('pending', 'Pending')], default='pending', max_length=255),
        ),
    ]
