# Generated by Django 5.1.4 on 2025-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildIT_API', '0013_projects_markdown_skills_category_skills_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='markdown',
            field=models.TextField(null=True),
        ),
    ]
