# Generated by Django 5.1.4 on 2024-12-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tagname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
