# Generated by Django 5.1.4 on 2024-12-16 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_users_firstname_alter_users_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='effort',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='placement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='priority',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='risk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
