# Generated by Django 5.1.4 on 2024-12-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_items_created_by_alter_items_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='placement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lists',
            name='placement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
