# Generated by Django 5.1.4 on 2024-12-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_items_created_by_alter_items_effort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
