# Generated by Django 5.1.4 on 2025-01-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_items_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='name',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='itemtags',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemtags', to='api.items'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='name',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tagname',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='users',
            name='tagname',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
