# Generated by Django 5.1.4 on 2025-01-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_users_pseudo_alter_boards_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.projects'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
