# Generated by Django 5.1.4 on 2025-01-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tags_project_alter_items_name_alter_users_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='name',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
