# Generated by Django 5.1.4 on 2025-01-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_lists_name'),
        ('api', '0013_projects_markdown_skills_category_skills_description_and_more'),
    ]

    operations = [
    ]
