# Generated by Django 5.1.4 on 2025-01-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_projects_markdown'),
        ('api', '0014_merge_20250115_0949'),
    ]

    operations = [
    ]
