# Generated by Django 5.1.4 on 2025-02-02 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20250116_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='chatroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chatrooms'),
        ),
        migrations.AlterField(
            model_name='boards',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='api.projects'),
        ),
        migrations.AlterField(
            model_name='boardskills',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boards'),
        ),
        migrations.AlterField(
            model_name='boardskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skills'),
        ),
        migrations.AlterField(
            model_name='dependencies',
            name='dependent_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_items', to='api.items'),
        ),
        migrations.AlterField(
            model_name='dependencies',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='api.items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users'),
        ),
        migrations.AlterField(
            model_name='items',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.lists'),
        ),
        migrations.AlterField(
            model_name='itemskills',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.items'),
        ),
        migrations.AlterField(
            model_name='itemskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skills'),
        ),
        migrations.AlterField(
            model_name='itemtags',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemtags', to='api.items'),
        ),
        migrations.AlterField(
            model_name='itemtags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tags'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='api.boards'),
        ),
        migrations.AlterField(
            model_name='listskills',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lists'),
        ),
        migrations.AlterField(
            model_name='listskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skills'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatrooms'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.projects'),
        ),
        migrations.AlterField(
            model_name='userchatrooms',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatrooms'),
        ),
        migrations.AlterField(
            model_name='userchatrooms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.items'),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects'),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skills'),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
    ]
